### ISSUE TITLE
How can I load locale programmatically?

### ISSUE THREAD

**Issue by omzer** [Skyost/EzLocalization#3]
I need to build an App where the user can set his own locale manually from the settings, is there's a way to load custom locale from dart code?

**Comment by Skyost** [comment]
Did you see #2 ?

**Comment by omzer** [comment]
@Skyost Yes I saw it, but I think having this kind of feature in EzLocalization will make it 1st localization library.

**Comment by Skyost** [comment]
Maybe adding a key like `preferredLocale` or something would be possible.

Anyway, if I can't add it, I will provide a code snippet for doing this using Provider.

**Comment by omzer** [comment]
Or you can suggest the user to turn his MaterialApp into a stateful widget if he is seeking such functionality.

In any case, this is just a suggestion, and thank you for the amazing work 👏.
