### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by jonafeucht** [Skyost/EzLocalization#4]
**Describe the bug**
I'm getting **_Another exception was thrown: A non-null String must be provided to a Text widget._** when trying to access json subtree.

This is how the json file looks like
```ruby
{
"bob": {
"text1": "Hello"
}
}
```

And this is how I'm getting it `Text(EzLocalization.of(context).get("bob.text1"),),`

**Comment by Skyost** [comment]
> Am I missing something?

I don't know, it also depends on your files structure, your current `MaterialApp`, ... Please follow the steps described [here](https://github.com/Skyost/EzLocalization#getting-started) and tell me back.

**Comment by jonafeucht** [comment]
> > Am I missing something?
> 
> I don't know, it also depends on your files structure, your current `MaterialApp`, ... Please follow the steps described [here](https://github.com/Skyost/EzLocalization#getting-started) and tell me back.

Massive facepalm on my part. My phone was on the wrong locale this whole time. lol
Sorry for taking up your time.

**Comment by Skyost** [comment]
No problem :wink:
