### ISSUE TITLE
Please support intl to 0.18.1

### ISSUE THREAD

**Issue by RoisNewVersion** [Skyost/EzLocalization#7]
**Is your feature request related to a problem? Please describe.**
Cannot use package intl 0.18.1 version

**Describe the solution you'd like**
Upgrade intl package to latest

**Describe alternatives you've considered**
-

**Additional context**
Cannot use ez_localization 1.1.0 if we upgrade intl package to 0.18.1

**Comment by Skyost** [comment]
Well, I think it is currently supported. Can you post the error message please ?

**Comment by RoisNewVersion** [comment]
Currently I install ez_localization: ^1.1.0 and intl: ^0.18.0. then when I want to update intl to 0.18.1, it give me warning like below.

`Because no versions of ez_localization match >1.1.0 <2.0.0 and ez_localization 1.1.0 depends on flutter_localizations from sdk, ez_localization ^1.1.0 requires flutter_localizations from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, ez_localization ^1.1.0 requires intl 0.18.0.
So, because notablonjo_online depends on both ez_localization ^1.1.0 and intl ^0.18.1, version solving failed.`

**Comment by Skyost** [comment]
Yeah, I think it's pretty clear :

`every version of flutter_localizations from sdk depends on intl 0.18.0`

The problem is with `flutter_localizations` from the SDK, not `ez_localization`.
